run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - revive
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true
