# GoReleaser configuration for jobcli
# See: https://goreleaser.com

version: 2

project_name: jobcli

changelog:
  disable: true

builds:
  - id: jobcli
    main: ./cmd/jobcli
    binary: jobcli
    ldflags: >-
      -s -w
      -X main.version={{ .Tag }}
      -X main.commit={{ .ShortCommit }}
      -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: jobcli_darwin
    main: ./cmd/jobcli
    binary: jobcli
    ldflags: >-
      -s -w
      -X main.version={{ .Tag }}
      -X main.commit={{ .ShortCommit }}
      -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - builds:
      - jobcli
      - jobcli_darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
